// Package todo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package todo

import (
	"time"
)

// CreateTodoDto defines model for CreateTodoDto.
type CreateTodoDto struct {
	Description string `json:"description"`
	Title       string `json:"title"`
}

// Todo defines model for Todo.
type Todo struct {
	CreatedAt     time.Time `json:"createdAt"`
	Description   string    `json:"description"`
	Finished      bool      `json:"finished"`
	Id            int       `json:"id"`
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
	Title         string    `json:"title"`
}

// UpdateTodoDto defines model for UpdateTodoDto.
type UpdateTodoDto struct {
	Description *string `json:"description,omitempty"`
	Finished    *bool   `json:"finished,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoDto

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoDto
