FROM mariadb:11.4.5

# Environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=todo
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin123

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_520_ci", "--skip-character-set-client-handshake"]