// Package auth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package auth

// LoginDto defines model for LoginDto.
type LoginDto struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

// LoginResponseDto defines model for LoginResponseDto.
type LoginResponseDto struct {
	Token *string `json:"token,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginDto
