// Package todo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package todo

import (
	"time"
)

// CreateTodoDto defines model for CreateTodoDto.
type CreateTodoDto struct {
	Description string `json:"description"`
	Title       string `json:"title"`
}

// Todo defines model for Todo.
type Todo struct {
	Completed     bool      `json:"completed"`
	CreatedAt     time.Time `json:"createdAt"`
	Description   string    `json:"description"`
	Id            string    `json:"id"`
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
	Title         string    `json:"title"`
}

// UpdateTodoDto defines model for UpdateTodoDto.
type UpdateTodoDto struct {
	Completed   *bool   `json:"completed,omitempty"`
	Description *string `json:"description,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoDto

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoDto
